apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pdf-creator
spec:
  template:
    spec:
      containers:
      - image: gcr.io/foritu-version1/app-web:app-web
        ports:
        - containerPort: 8080
        env:
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: SUPABASE_URL
                key: latest
          - name: SUPABASE_KEY
            valueFrom:
                secretKeyRef:
                name: SUPABASE_KEY
                key: latest
          - name: SUPABASE_BUCKET
            valueFrom:
                secretKeyRef:
                name: SUPABASE_BUCKET
                key: latest
