apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pdf-creator
spec:
  template:
    spec:
      containers:
      - image: gcr.io/foritu-version1/app-web:app-web
        ports:
        - containerPort: 8080
        env:
        - name: SUPABASE_URL
          value: "https://kjoenbrfqxljeklnmbev.supabase.co"
        - name: SUPABASE_KEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqb2VuYnJmcXhsamVrbG5tYmV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUxMTIxMzAsImV4cCI6MjA0MDY4ODEzMH0.nHwB5kF4CybdoidcPTQZWd-vCHVgq4QTgXVPpRsC5Bo"
        - name: SUPABASE_BUCKET
          value: "qr_pdf"
